#!/bin/bash
#===================================================================================
# LABADMIN SCRIPT SERVER CONFIG
#         FILE: config
#  DESCRIPTION: Labadmin script server client config variables
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#      LICENSE: GNU General Public License v3.0
#      VERSION: 2023.04
#      CREATED: 25.04.2023
#=================================================================================== 

#===============================================================================
#  GLOBAL CONFIG VARIABLES
#===============================================================================
readonly log_mail="logs.carlos3@gmail.com"								# Email to send log errors
readonly sethostname_script="LSS SET HOSTNAME"								# Hostname script in respositories to change hostname
readonly check_hostnames="true"											# Empty value for no set hostnames from inventory

readonly repositories_path="${lss_path}/repositories/"					# Base path of scripts repositories dirs: linux, w7, w10, etc.
readonly inventories_path="${lss_path}/inventories/"					# Base path of inventories config files
readonly inventory_path="${inventories_path}/default.inventory"			# Inventory config file used
