#!/usr/bin/env bash
#===================================================================================
# LABADMIN SCRIPT SERVER
#         FILE: lss-hosts
#        USAGE: lss-hosts
#
#  DESCRIPTION: Labadmin script server hosts info
#               Manage actions to do: list pending scripts, show script code, save exec status (exec_ok or exec_error)
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#	   LICENSE: GNU General Public License v3.0
#      VERSION: 2022.06
#      CREATED: 28.06.2022
#=================================================================================== 

#===============================================================================
#  GLOBAL VARIABLES
#===============================================================================
# Base path of scripts repositories dirs: linux, w7, w10, etc.
# Make sure ssh user has read permissions and write permission in log files!
readonly repositories_path=$(dirname "$(readlink -f "$0")")		

# LOAD CONFIG VARIABLES
source "${repositories_path}/config"
