#!/usr/bin/env bash
#===================================================================================
# LABADMIN SCRIPT MANAGER
#         FILE: lss-manager
#        USAGE: lss-manager [repository]
#
#  DESCRIPTION: Labadmin Script Server Manager for script configuration and log viewer
#               CLI to interac over scripts and logs
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#	   LICENSE: GNU General Public License v3.0
#      VERSION: 2026.05
#      CREATED: 2022.06.28
#=================================================================================== 

#===============================================================================
#  GLOBAL VARIABLES
#===============================================================================
readonly lss_path=$(dirname "$(readlink -f "$0")")				# LSS root path
readonly lssinventory_path="${lss_path}/lss-inventory"			# lss-inventory executable path
unset repository												# Current selected repository
unset repository_path											# Current selected repository path
unset script_name												# Current selected script name
unset script_cat												# Current selected script category
unset script_path												# Current selected script path
unset scripts													# Array for list of scripts loades
unset menu_path													# Temp dir to create file for read autocomplete
unset action													# Current selected action
unset action_params												# Current selected actions optional parameters


#===============================================================================
#  LOAD CONFIG
#===============================================================================
source "${lss_path}/config"


#===============================================================================
#  COLORS AND FORMAT
#===============================================================================
S_R="\e[0m"            		# Reset all attributes
S_B="\e[1m"             	# Style BOLD
S_D="\e[2m"		         	# Style DIM
S_U="\e[4m"            		# Style UNDERLINE
S_I="\e[7m"             	# Style INVERTED
S_DL="\e[K"             	# Style DELETE TO END OF LINE
cursor_save()		 { echo -en "\e[s"; }			# Cursor SAVE POSITION
cursor_restore()	 { echo -en "\e[u"; }			# Cursor RESTORE POSITION
cursor_hide()		 { echo -en "\e[?25l"; }		# Cursor HIDE CURSOR
cursor_show()		 { echo -en "\e[?25h"; }		# Cursor SHOW CURSOR
cursor_move-up()	 { echo -en "\e[${1}A"; }		# Cursor MOVE UP $1 LINES
cursor_move-down()	 { echo -en "\e[${1}B"; }		# Cursor MOVE DOWN $1 LINES
cursor_move-left()	 { echo -en "\e[${1}D"; }		# Cursor MOVE LEFT $1 COLS
cursor_move-right()  { echo -en "\e[${1}C"; }		# Cursor MOVE RIGHT $1 COLS
cursor_move-begin()  { echo -en "\r"; }             # Cursor MOVE BEGIN POSITION IN CURRENT LINE
cursor_move-pos()    { echo -en "\e[${1};${2}H"; }  # Cursor MOVE LINE $1 COL $2
C_D="\e[39m"            	# Color DEFAULT
C_R="\e[31m"            	# Color RED
C_BR="\e[1m\e[31m"      	# Color BOLD RED
C_LR="\e[38;5;196m"         # Color LIGHT RED
C_G="\e[32m"            	# Color GREEN
C_BG="\e[1m\e[32m"      	# Color BOLD GREEN
C_LG="\e[38;5;112m"        	# Color LIGHT GREEN
C_Y="\e[33m"            	# Color YELLOW
C_BY="\e[1m\e[33m"      	# Color BOLD YELLOW
C_LY="\e[38;5;185m"         # Color LIGHT YELLOW
C_B="\e[34m"            	# Color BLUE
C_BB="\e[1m\e[34m"      	# Color BOLD BLUE
C_LB="\e[38;5;110m"    	 	# Color LIGHT BLUE
C_M="\e[35m"            	# Color MAGENTA
C_BM="\e[1m\e[35m"      	# Color BOLD MAGENTA
C_LM="\e[38;5;182m"        	# Color LIGHT MAGENTA
C_C="\e[36m"            	# Color CYAN
C_BC="\e[1m\e[36m"      	# Color BOLD CYAN
C_LC="\e[38;5;159m"        	# Color LIGHT CYAN
C_N="\e[38;5;241m"          # Color GREY
C_LN="\e[38;5;248m"         # Color LIGHT GREY
B_R="\e[41m"            	# Background RED
B_G="\e[42m"            	# Background GREEN
B_Y="\e[43m"            	# Background YELLOW
B_B="\e[44m"            	# Background BLUE
B_M="\e[45m"            	# Background MAGENTA
B_C="\e[46m"            	# Background CYAN
B_LG="\e[47m"           	# Background LIGHT GREY
B_DG="\e[100m"          	# Background DARK GREY
B_LR="\e[101m"          	# Background LIGHT RED
B_LG="\e[102m"          	# Background LIGHT GREEN
B_LY="\e[103m"          	# Background LIGHT YELLOW
B_LB="\e[104m"          	# Background LIGHT BLUE
B_LM="\e[105m"          	# Background LIGHT MAGENTA
B_LC="\e[106m"          	# Background LIGHT CYAN
B_W="\e[107m"           	# Background LIGHT WHITE





#=== FUNCTION ==================================================================
#        NAME: show_header
# DESCRIPTION: show header and cleaer screen
#===============================================================================
function show_header() {
	header_width=120; [ "$COLUMNS" -lt 120 ] && header_width=$(($COLUMNS-4))
	echo -e "${C_LN} ┌$(seq -s "─" 1 $header_width | tr -d [0-9])┐"
	echo -e " │$(seq -s " " 1 $(((header_width-22)/2)) | tr -d [0-9])${C_D}${S_B}LABADMIN SCRIPT SERVER${S_R}${C_LN}$(seq -s " " 1 $(((header_width-22)/2)) | tr -d [0-9]) │"
	echo -e " └$(seq -s "─" 1 $header_width | tr -d [0-9])┘${C_D}"
}



#=== FUNCTION ==================================================================
#        NAME: show_menu
# DESCRIPTION: show list of current repository scripts and log statics
# GLOBAL VARIABLES MODIFIED
#	$scripts[]
#===============================================================================
function show_menu() {
	local f_filter f_trash								# filter flag, trash flag
	local filter="$1"									# optional filter list
	[ "${filter}" ] && f_filter="true"
	[ "${filter,,}" = "trash" ] && f_trash="true"		# flag to show trashed scripts on list

	cursor_hide
	echo -en "\n  ${C_LN}Updating scripts info...${C_D}"
	menu="  ${S_B}\tCATEGORY\tRE\tSCRIPT\tFLAG\tSELECT\tGET\tOK\tERROR\tLAST${S_R}\n"

	# Create sloc variable with script list orderer by category
	sloc=""
	for s in "${repository_path}"/*/log "${repository_path}"/.TRASH/*/log; do
		s="${s%/log}"
		[ ! "$f_trash" ] && [[ "${s%/*}" = */.TRASH ]] && continue		# Skip /.TRASH scripts if no flag trash
		unset c
		[ -e "${s}/category" ] && c=$(cat "${s}/category"); [ ! "$c" ] && c="none"
		[ -f "${s}/disable" ] && d="A" || d="Z"							# Order disabled scripts first in his category
		[[ "${c^^}" = @("LABADMIN"|"LSS") ]] && c="000"					# Order LABADMIN category first
		[ "${c}" = "none" ] && c="ZZY"									# Order no category last
		[ "${c^^}" = "TRASH" ] && c="ZZZ"								# Order trash scripts last
		sloc="${sloc}${sloc:+\n}${c}\t${d}\t${s}"
	done
	sloc=$(echo -e "$sloc" | sort -k1,1 -k2,2 -k3,3)
	clc=$(echo "$sloc" | cut -f1 | uniq -c | awk '{print $1}')
	sloc=$(echo "$sloc" | cut -f3-)

	# Create menu variable with script list
	i=0; unset scripts
	while read s; do
		local sp="${s}"
		s=$(basename "$s")
		i=$((i+1))
		scripts[$i]="$s"		# Update scripts[]

		unset sc
		[ -e "${sp}/category" ] && sc=$(cat "${sp}/category"); [ ! "$sc" ] && sc="${C_N}none${S_R}"
		scripts_cat[$i]="${sc}"
		[ "$f_filter" ] && [[ "${sc,,}" != *"$filter"* ]] && continue
		local f=" " ci="${C_D}" cl="${C_D}"
		[ -e "${sp}/disable" ] && { ci="${C_R}"; cl="${C_LN}"; }							# Colors when disabled index and line
		[ -e "${sp}"/disable ] && f="${f}${C_R}D${cl}"										# Flag disabled
		[ -e "${sp}"/priority ] && f="${f}${C_LB}P${cl}"									# Flag priority
		[ -e "${sp}"/first ] && f="${f}${C_LG}F${cl}"										# Flag first
		[ -e "${sp}"/nosavelog ] && f="${f}${C_Y}L${cl}"									# Flag nosavelog
		[ "$s" = "${script_name}" ] && cc=">${S_B}" || cc=" "										# Colors when selected script

		local st=$(grep "readonly select_type" "${sp}"/select | cut -f2 -d\")				# Select type script (once, always, custom)
		local l="$(grep -o -F -e " [GET] " -e " [EXEC_OK] " -e " [EXEC_ERROR] " "${sp}"/log | sort | uniq -c)"
		local ng=$(echo "$l" | grep -F "[GET]" | awk '{print $1}');			[ ! "$ng" ] && ng=0												# get count
		local no=$(echo "$l" | grep -F "[EXEC_OK]" | awk '{print $1}');		[ ! "$no" ] && no=0												# ok count
		local ne=$(echo "$l" | grep -F "[EXEC_ERROR]" | awk '{print $1}');  [ ! "$ne" ] && ne=0; [ "$ne" -gt 0 ] && ne="${C_R}${ne}"		# error count
		local t=$(tail -1 "${sp}"/log  | cut -f1 -d" " | tr -d "][" | tr "_" " ")													# last log time
		if [ ! "$t" ]; then t="\e[38;5;241m-"
		else t=$(($(date +%s)-$(date -d "$t" +%s))); local td="$((t/86400))" th="$(((t%86400)/3600))" tm="$(((t%3600)/60))"
		[ "$td" -gt 0 ] && t="\e[38;5;241m${td}d" || { [ "$th" -gt 0 ] && t="\e[38;5;245m${th}h" || t="\e[38;5;249m${tm}m"; }; fi
		menu="$menu\n ${cc}${ci}[$i]${C_D}${cl}\t${sc}\t${s/ /$'\t'}\t${f}\t${st}\t${ng}${lg}\t${no}$lo\t${ne}${S_R}${C_D}\t${C_LN}${t}"
	done <<< "$sloc"

	echo -en "\n\e[2A                                           "	# Overwrite Updating scripts info... line
	menu=$(echo -e "${menu}" | column -t -s $'\t' -R 6,7,8,9)

	# Add header and footer separator lines
	local bar="  $(echo -e "${C_LN}")$(seq -s"─" 1 $(($(echo "$menu" | head -1 | wc -c)-8)) | tr -d "[0-9]")$(echo -e "${C_D}")"
	menu=$(echo "${menu}" | sed "2i\\${bar}")$'\n'"${bar}"	# Add bars after format columns
	# Add category separator lines
	if [ ! "$f_filter" ]; then
		local bar2="$(echo -e "${S_D}")      $(echo -e "${C_LN}")$(seq -s"-" 1 $(($(echo "$menu" | head -1 | wc -c)-14)) | tr -d "[0-9]")$(echo -e "${C_D}")$(echo -e "${S_R}")"
		n=0
		for cl in $(echo "$clc" | head -n -1); do
			[ "$n" -eq 0 ] && n="$cl" || n=$((n+cl+1))
			menu=$(echo "$menu"| sed "$((n+3))i\\${bar2}")
		done
	fi

	menu="\n${menu}\n"

	echo -e "$menu"
	cursor_show
}


#=== FUNCTION ==================================================================
#        NAME: change_repository
# DESCRIPTION: change current repository and show menu
# PARAMETERS
#	$1		repository name
#
# GLOBAL VARIABLES MODIFIED
#	$repository
#	$repository_path
#	$script_name
#	$scripts
#
# RETURN
#	0 if repository change is ok
#	1 if cant change repository (not exists?)
#===============================================================================
function change_repository() {
	local r="$1"

	# Check if exist repository
	[ ! -d "${repositories_path}/${r}" ] && return 1
	[[ $(readlink -f "${repositories_path}/${r}") = $(readlink -f "${repositories_path}") ]] && return 1		# Check if try directory outside repositories_path
	[[ $(readlink -f "${repositories_path}/${r}") != $(readlink -f "${repositories_path}")* ]] && return 1		# Check if try directory outside repositories_path

	([ ! "$repository" ] || [ "$repository" != "$r" ]) && clear
	show_header
	repository="$r"
	repository_path="${repositories_path}/${repository}/"
	unset script_name
	unset script_cat
	unset script_path
	unset scripts

	show_menu
	return 0
}


#=== FUNCTION ==================================================================
#        NAME: read_action
# DESCRIPTION: prompt for action to exec and change repository
# GLOBAL VARIABLES MODIFIED
#	$action
#	$action_params
#===============================================================================
function read_action() {
	# Generate actions files for read tab autocomplete
	if [ ! "$menu_path" ]; then
	   menu_path=$(mktemp -d)
	   mkdir "${menu_path}/script" "${menu_path}/root"
	   cd "${menu_path}/root/"; touch cd create help list
	   cd "${menu_path}/script/"; touch bash  delete  set-name  set-RE  set-category  disable  enable  priority  first  nosavelog log  status  map  log-clean  log-wipe  ls  script  select trash untrash
	fi
	cd "${menu_path}/$([ "$script_name" ] && echo "script" || echo "root")"

	# Read prompt: repository/script selected>
	local prompt="  ${C_Y}${repository}${C_D}$([ "$script_name" ] && echo "/${C_Y}${script_name}${C_D}")> "
	read -r -e  -p "$(echo -e "$prompt")" action

	action="$(echo "$action" | xargs)"		# Trim and compact spaces
	action_params="${action#* }"
	[ "$action_params" = "$action" ] && action_params=""
	action="${action%% *}"

	# Empty action: list
	if [ ! "$action" ]; then
		action="list"

	# Action <n>: cd <n>
	elif [ "$action" -eq "$action" ] &>/dev/null; then
		action_params="$action"
		action="cd"

	# Action repository name
	elif change_repository "$action"; then
		action="none"
	fi
}


#=== FUNCTION ==================================================================
#        NAME: action_none
# DESCRIPTION: empty action (do nothing and show menu again)
#===============================================================================

function action_none() {
	return
}



#=== FUNCTION ==================================================================
#        NAME: action_cd
# DESCRIPTION: change selected script according $action and $actions_params
#				cd | cd .. 	unselect current script
#				cd <n>		select <n> script
#				cd <str>	select string contaning <str> in name
#
# GLOBAL VARIABLES MODIFIED
#   $action
#   $action_params
#===============================================================================
function action_cd() {
		# cd parent
        if [ ! "$action_params" ] || [ "$action_params" = ".." ]; then
            action_..

		# cd <n>
		elif [ "$action_params" -eq "$action_params" ] &>/dev/null; then
            script_name="${scripts[$action_params]}"
            [ ! "$script_name" ] && echo -e "  ERROR: invalid script number\n"
			script_cat="${scripts_cat[$action_params]}"

		# cd <string>
		else
            local l=""
            l=$(for i in ${!scripts[@]}; do
				echo "${scripts[$i]}" | grep -Fiq "$action_params" && echo "$i"
            done)
            if [ $(echo "$l" | wc -l) -gt 1 ]; then
				IFS=$'\n'
				for i in $l; do
					echo "   ${scripts[$i]}"
    			done
				IFS=$'\n\t '
				echo
            elif [ "$l" ]; then
                script_name="${scripts[$l]}"
                script_cat="${scripts_cat[$l]}"
            else
                echo "  ERROR: script not found $action_params\n"
            fi
        fi

		if [ "${script_cat^^}" = "TRASH" ]; then
			script_path="${repository_path}/.TRASH/${script_name}"
		else
			script_path="${repository_path}/${script_name}"
		fi
}



#=== FUNCTION ==================================================================
#        NAME: exec_action
# DESCRIPTION: exec function of selected action
#===============================================================================
function exec_action() {
	action_function="action_${action}"
	if [ "$(type -t "$action_function")" != "function" ]; then
		echo -e "  Unrecognized action: $action\n"
		return 1
	fi
	"$action_function"
}


#=== FUNCTION ==================================================================
#        NAME: action_help
# DESCRIPTION: action_h alias
#===============================================================================
function action_help() {
	action_h
}


#=== FUNCTION ==================================================================
#        NAME: action_h
# DESCRIPTION: action to show help
#===============================================================================
function action_h() {
	echo -e "
   Global actions:
    ${S_B}list${S_R} [CATEGORY]\tList scripts and stats. Optionaly filter by category
    ${S_B}create${S_R}\tCreate new script folder with default template files
    ${S_B}cd${S_R} <n>\tSelect script number <n>
    ${S_B}<n>${S_R}\tSelect script number <n>
    ${S_B}cd${S_R} <str>\tSelect script contaning str in name
    ${S_B}<repo>${S_R}\tChange to repository <repo>

   Script status actions:
    ${S_B}status${S_R} [RE]\tShow exec stats of selected script. Optionaly filter hosts by RE
    ${S_B}map${S_R} [LAB...]\tShow exec stats in a map. Optionaly show only a list of LABS
    ${S_B}log${S_R} [RE]\tShow log file of selected script. Optionaly filter lines by RE
    ${S_B}log-wipe${S_R}\tWipe log file of selected script
    ${S_B}log-clean${S_R}\tClean all log error entries in log file of selected script

   Script manage actions:
    ${S_B}bash${S_R}\tOpen Bash in selected script directory
    ${S_B}script${S_R}\tShow script file of selected script
    ${S_B}select${S_R}\tShow select file of selected script
    ${S_B}set-name${S_R} <name>\tChange name of selected script
    ${S_B}set-RE${S_R} <re>\tChange RE of selected script
    ${S_B}set-category${S_R} <cat>\tChange caregory of selected script

   Script remove actions:
    ${S_B}delete${S_R}\tDelete selected script permanently
    ${S_B}trash${S_R}\tMove to trash selected script
    ${S_B}untrash${S_R}\tRestore selected script from trash
    ${S_B}list${S_R} trash\tList thrased scripts

   Script flag actions:
    ${S_B}enable${S_R}\tUnset disable flag (D)
    ${S_B}disable${S_R}\tSet disable flag (D)
    ${S_B}priority${S_R}\tToogle priority flag (P) (exec only priority scripts if any selected)
    ${S_B}first${S_R}\tToogle first flag (F) (exec first this scripts on list)
    ${S_B}nosavelog${S_R}\tToogle nosavelog flag (L) (minimize logs on server and clients)

    " | column -L -t -s $'\t'
}


#=== FUNCTION ==================================================================
#        NAME: action_l
# DESCRIPTION: action to show scripts menu
#===============================================================================
function action_l() {
	show_menu "${action_params}"
}


#=== FUNCTION ==================================================================
#        NAME: action_list
# DESCRIPTION: action to show scripts menu
#===============================================================================
function action_list() {
	show_menu ${action_params}
}


#=== FUNCTION ==================================================================
#        NAME: action_create
# DESCRIPTION: create new empty script
#===============================================================================
function action_create() {
    read -r -p "  Regular expresion and Description: " s
	d=$(echo "$s" | awk '{print $2}'); [ ! "$d" ] && { echo -e "  ERROR: empty description\n"; return 1; }

	local sp="${repository_path}/${s}"
	[ -e "${sp}" ] && { echo -e "  ERROR: script $s already exists\n"; return 1; }

	read -r -p "  Category: " c
	c=$(echo "${c^^}" | awk '{print $1}')
	[[ "${c,,}" = @(trash|untrash) ]] && { echo "  ERROR: reserved category\n"; return 1; }

	mkdir "${sp}" || return 1
    touch "${sp}/disable"                               # Start disabled
    touch "${sp}/log" "${sp}/script" "${sp}/select"
	echo "${c}" > "${sp}/category"
	mkdir "${sp}/logs"
    chmod ug+w "${sp}/log" "${sp}/logs"
	[ $(id -u) -eq 0 ] && chown -R lss-admin:lss-agent "${repository_path}"

echo '#!/usr/bin/env bash
#===================================================================================
# SELECT SCRIPT
#         FILE: select
#        USAGE: select HOSTNAME MAC HOSTNAME_INVENTORY AGENT_VERSION
#
#  DESCRIPTION: Check if hostname is selected for exec this script or not (exit with 0 or 1)
#               Use select_type variable to config select beahvior.
#               Optionaly compelte select_custom() for custom selection
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#      LICENSE: GNU General Public License v3.0
#      VERSION: 2024.11
#      CREATED: 2022.06.01
#===================================================================================


#===============================================================================
#  CONFIG SELECT TYPE BEAHVIOR
#===============================================================================
readonly select_type="once"     # always|once|custom



#===============================================================================
#  GLOBAL VARIABLES
#===============================================================================
readonly hostname="$1"                                  # Current host local hostname
readonly mac="$2"                                       # Current hot MAC
readonly hostname_inventory="$3"                        # hostname from inventory for MAC
readonly agent_version="$4"								# agent version
readonly log_path="$(dirname "${BASH_SOURCE[0]}")/log"


#=== FUNCTION ==================================================================
#        NAME: select_always
# DESCRIPTION: select script for exec everytime
#===============================================================================
function select_always() {
    exit 0
}

#=== FUNCTION ==================================================================
#        NAME: select_once
# DESCRIPTION: select script for exec only once time (first exec ok)
#===============================================================================
function select_once() {
    # Search by hostname or MAC?
    [ "$mac" ] && [ "$mac" != "00:00:00:00:00:00" ] && id_search="$mac" || id_search="$hostname"

    # Search in log if hostname had executed OK this script
    grep -F "[${id_search}]" "$log_path" | grep -qF "[EXEC_OK]"
    [ $? -eq 0 ] && exit 1 || exit 0
}


#=== FUNCTION ==================================================================
#        NAME: select_custom
# DESCRIPTION: select script for custom code
#===============================================================================
function select_custom() {
    echo "Complete select_custom function"
    exit 1
}

# Exec select function according $select_type content
"select_${select_type}"' > "${sp}/select"


	echo -e "  Script directory: ${S_B}${sp}${S_R}/"
	echo

	script_name="${s}"
	script_cat="${c}"
	script_path="${sp}"
}


#=== FUNCTION ==================================================================
#        NAME: action_delete
# DESCRIPTION: action to delete selected script
#===============================================================================
function action_delete() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
    read -r -p "  Sure? Script and logs will be removed (N/y) " r
    if [ "${r,,}" = "y" ]; then
		[ ! -d "${script_path}" ] && { echo -e "ERROR: directory ${S_B}${script_path}${S_R} not exists! (bug error?)\n"; return 1; }
		echo -e "  Removing script ${S_B}${script_path}${S_R}"
        rm -rf "${script_path}" || return 1
		action_..
    fi
    echo
}


#=== FUNCTION ==================================================================
#        NAME: action_set-name
# DESCRIPTION: action to set name of selected script
#===============================================================================
function action_set-name() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local sd
	[ "$action_params" ] && sd="$action_params" || read -r -p "  New name: " sd
	local sn="${script_name%% *} ${sd}"
	local sp="$(dirname "${script_path}")/${sn}"

	[ -e "${sp}" ] && { echo -e "  ERROR: already exist script ${S_B}${sp}${S_R}"; return 1; }
	echo -e "  Renaming script to ${S_B}${sp}${S_R}"
	mv "${script_path}" "${sp}" || return 1
	echo

	script_name="${sn}"
	script_path="${sp}"
}


#=== FUNCTION ==================================================================
#        NAME: action_set-RE
# DESCRIPTION: action to set REGEX of selected script
#===============================================================================
function action_set-RE() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local sre
	[ "$action_params" ] && sre="$action_params" || read -r -p "  New REGEX: " sre
	local sn="${sre} ${script_name#* }"
	local sp="$(dirname "${script_path}")/${sn}"

	[ -e "${sp}" ] && { echo -e "  ERROR: already exist script ${S_B}${sp}${S_R}"; return 1; }
	echo -e "  Renaming script to ${S_B}${sp}${S_R}"
	mv "${script_path}" "${sp}" || return 1
	echo

	script_name="${sn}"
	script_path="${sp}"
}


#=== FUNCTION ==================================================================
#        NAME: action_set-category
# DESCRIPTION: action to set category of selected script
#===============================================================================
function action_set-category() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	[ "${script_cat^^}" = "TRASH" ] && { echo -e "  ERROR: cant set category from trash scripts\n"; return 1; }

	local sc
	[ "$action_params" ] && sc="$action_params" || read -r -p "  New category: " sc
	[[ "${sc^^}" = @(TRASH|UNTRASH) ]] && { echo -e "  ERROR: reserved category\n"; return 1; }

	sc=$(echo "${sc^^}" | awk '{print $1}')

	local f="${script_path}/category"
	echo -e "  Setting category ${S_B}${sc}${S_R} to ${S_B}${f}${S_R}"
	echo "$sc" > "${f}"
	echo

	script_cat="$sc"
}


#=== FUNCTION ==================================================================
#        NAME: action_exit
# DESCRIPTION: action to exit
#===============================================================================
function action_exit() {
	echo
	exit 0
}


#=== FUNCTION ==================================================================
#        NAME: action_q
# DESCRIPTION: action to exit
#===============================================================================
function action_q() {
	echo
	exit 0
}



#=== FUNCTION ==================================================================
#        NAME: action_log
# DESCRIPTION: action to call specific log subaction according $action_params
#===============================================================================
function action_log() {
		action_log-show
}


#=== FUNCTION ==================================================================
#        NAME: action_log-show
# DESCRIPTION: action to show log file of selected script
#===============================================================================
function action_log-show() {
    [ "$script_name" ] && local f="${script_path}/log" || local f="${repository_path}/log"       # Log file path

	echo
	echo -e "  File ${S_B}${f//\/\//\/}${S_R}"
	echo -en "${C_LN}"; seq -s "-" 1 $((COLUMNS)) | tr -d "[0-9]"; echo -en "${C_D}"
	[ "$action_params" ] && echo -e "  ${C_LN}Filtering lines by:${C_D} $action_params"
	egrep -i --color "${action_params}" "$f" | less +G
	echo -en "${C_LN}"; seq -s "-" 1 $((COLUMNS)) | tr -d "[0-9]"; echo -e "${C_D}"
}


#=== FUNCTION ==================================================================
#        NAME: action_status
# DESCRIPTION: action to show exec status of selected script
#===============================================================================
function action_status() {
    [ "$script_name" ] && local f="${script_path}/log" || local f="${repository_path}/log"       # Log file path

	echo
	echo -e "  File stats from file ${S_B}${f//\/\//\/}${S_R}"
	echo -en "${C_LN}"; seq -s "-" 1 $((COLUMNS)) | tr -d "[0-9]"; echo -en "${C_D}"

	[ "$action_params" ] && echo -e "  ${C_LN}Filtering hosts by:${C_D} $action_params"
	local i=1 n_get=0 n_ok=0 n_error=0 n_pending=0
	pad1="         "; pad2="                         "
	for h in $(awk '{print $3}' "$f" | sort -u | grep "$action_params" | sed -E 's/^\[||\]$//g'); do
		h_log=$(grep -F "[$h]" "$f")
		h_last=$(echo "$h_log" | tail -1 | cut -f1 -d" " | tr -d "[]" | tr "_" " ")
		h_get=$(echo "$h_log" | grep -Fc "[GET]")
		h_ok=$(echo "$h_log" | grep -Fc "[EXEC_OK]")
		h_error=$(echo "$h_log" | grep -Fc "[EXEC_ERROR]")
		h_pending="                   "; echo "$h_log" | tail -1 | grep -vqiF "[EXEC_OK]" && { h_pending="  ${C_R}PENDING!${S_R}         ";  n_pending=$((n_pending+1)); }
		n_get=$((n_get+h_get)); n_ok=$((n_ok+h_ok)); n_error=$((n_error+h_error));
		echo -e "${C_LN}${pad1:${#i}}$i${C_D}  ${h}$([ "$h_get" -gt 0 ] && echo "${C_Y}")${pad2:$((${#h}+${#h_get}))}  ${h_get}${S_R} GET$([ "${h_ok}" -gt 0 ] && echo "${C_G}")${pad1:${#h_ok}}${h_ok}${S_R} OK$([ "$h_error" -gt 0 ] && echo "${C_R}")${pad1:${#h_error}}${h_error}${S_R} ERRORS${h_pending}${C_LN}(${h_last})${C_D}"
		i=$((i+1))
	done
	echo -e "${C_LN}  ------------------------------------------------------------------------------------${C_D}"
	echo -e "${pad1}    ${pad2:${#n_get}}${C_Y}${n_get}${S_R} GET${pad1:${#n_ok}}${C_G}${n_ok}${S_R} OK${pad1:${#n_error}}${C_R}${n_error}${S_R} ERRORS   ${C_R}${n_pending}${S_R} PENDING!"
	echo
}


#=== FUNCTION ==================================================================
#        NAME: action_map
# DESCRIPTION: action to show exec status map of selected script
#===============================================================================
function action_map() {
    [ "$script_name" ] && local f="${script_path}/log" || { local f="${repository_path}/log"; action_params="*"; }       # Log file path

	# Select hosts to color
	local h hg hr hy h_log=$(awk '{print $3,$4}' "$f" | tr -d "[]") IFS=$'\n'
	local ha; declare -A ha
	for h in $h_log; do	ha["${h%% *}"]="${h##* }"; done	
	for h in ${!ha[@]}; do
		case ${ha[$h]} in
			EXEC_OK)      hg="${hg} ${h}"		;;
			EXEC_ERROR)   hr="${hr} ${h}"		;;
			*)            hy="${hy} ${h}"		;;
		esac
	done
	IFS='$\n\t '

#	local hg="" hr="" hy="" h_log=$(awk '{print $3,$4}' "$f")
#	for h in $(echo "$h_log" | cut -f1 -d" "| sort -u | sed -E 's/^\[||\]$//g'); do
#		case $(echo "${h_log}" | grep -F "[${h}]" | tail -1 | cut -f2 -d" ") in
#			\[EXEC_OK\])      hg="${hg} ${h}"		;;
#			\[EXEC_ERROR\])   hr="${hr} ${h}"		;;
#			*)                hy="${hy} ${h}"		;;
#		esac
#	done

	if [ "$action_params" ] ; then
		# Show only selected maps by params
		local d="d"; echo "$action_params" | grep -qF "*" && d="D"
		bash "${lssinventory_path}" map -H -g "$hg" -y "$hy" -r "$hr" -$d "$action_params"  
	else
		# Show maps according script RE
		bash "${lssinventory_path}" map -H -g "$hg" -y "$hy" -r "$hr" -D "${script_name%% *}" 
	fi
	echo
}

#=== FUNCTION ==================================================================
#        NAME: action_script
# DESCRIPTION: action to show script file content of selected script
#===============================================================================
function action_script() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local f="${script_path}/script"
	echo
	echo -e "  File ${S_B}${f}${S_R}"
	echo -en "${C_LN}"; seq -s "-" 1 $((COLUMNS)) | tr -d "[0-9]"; echo -en "${C_D}"
	cat "${f}"
	echo -en "${C_LN}"; seq -s "-" 1 $((COLUMNS)) | tr -d "[0-9]"; echo -e "${C_D}"
}


#=== FUNCTION ==================================================================
#        NAME: action_select
# DESCRIPTION: action to show select file content of selected script
#===============================================================================
function action_select() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local f="${script_path}/select"
	echo
	echo -e "  File ${S_B}${f}${S_R}"
	echo -en "${C_LN}"; seq -s "-" 1 $((COLUMNS)) | tr -d "[0-9]"; echo -en "${C_D}"
	cat "$f"
	echo -en "${C_LN}"; seq -s "-" 1 $((COLUMNS)) | tr -d "[0-9]"; echo -e "${C_D}"
}


#=== FUNCTION ==================================================================
#        NAME: action_bash
# DESCRIPTION: action to open Bash in selected script folder
#===============================================================================
function action_bash() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local d="${script_path}/"
	echo -e "  Opening shell in ${S_B}${d}${S_R}"
	echo
	(cd "$d"; env PS1="  [LSS-BASH]\e[0m:\[\e[1m\e[38;5;12m\]\W\[\e[0m\]]\$ " bash --norc)
	echo
}


#=== FUNCTION ==================================================================
#        NAME: action_log-wipe
# DESCRIPTION: action to wipe log file of selected script
#===============================================================================
function action_log-wipe() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	read -r -p "  Sure? All log data will be removed (N/y) " r
	if [ "${r,,}" = "y" ]; then
		local f="${script_path}/log"
		echo -e "  Wiping file ${S_B}${f}${S_R}"
		echo -n "" > "$f"
	fi
	echo
}


#=== FUNCTION ==================================================================
#        NAME: action_log-clean
# DESCRIPTION: action to clean all log error entries in log file of selected script
#===============================================================================
function action_log-clean() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
    read -r -p "  Sure? All errors log data will be removed (N/y) " r
    if [ "${r,,}" = "y" ]; then
		local f="${script_path}/log"
        echo -e "  Cleaning errors in file ${S_B}${f}${S_R}"
		sed -i "/ERROR\]/d" "$f"
	fi
    echo
}


#=== FUNCTION ==================================================================
#        NAME: action_disable
# DESCRIPTION: action to disable selected script
#===============================================================================
function action_disable() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
    local f="${script_path}/disable"
	echo -e "  Disabling script flag ${S_B}${f}${S_R}"
	touch "${f}"
	echo
}


#=== FUNCTION ==================================================================
#        NAME: action_enable
# DESCRIPTION: action to enable selected script
#===============================================================================
function action_enable() {
    [ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
    local f="${script_path}/disable"
    echo -e "  Enabling script flag ${S_B}${f}${S_R}"
    rm -f "${f}"
    echo
}


#=== FUNCTION ==================================================================
#        NAME: action_trash
# DESCRIPTION: action to move script to trash
#===============================================================================
function action_trash() {
    [ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	[ "${script_cat^^}" = "TRASH" ] && { echo -e "  ERROR: script already in trash\n"; return 1; }

	local sp="${repository_path}/.TRASH/${script_name}"
	[ -d "${sp}" ] && { echo -e "  ERROR: already exists script ${S_B}${script_name}${S_R} in trash\n"; return 1; }

    read -r -p "  Sure? Script will be move to trash (N/y) " r
    if [ "${r,,}" = "y" ]; then
        echo -e "  Moving to trash script ${S_B}${script_path}${S_R}"
		[ ! -d "${repository_path}/.TRASH/" ] && { mkdir -p "${repository_path}/.TRASH/" || return 1; }
		mv "${script_path}" "${sp}" || return 1
		echo TRASH > "${sp}/category"
		touch "${sp}/disable"

	    script_cat="TRASH"
	    script_path="${sp}"
    fi
    echo
}


#=== FUNCTION ==================================================================
#        NAME: action_untrash
# DESCRIPTION: action to restore script from trash
#===============================================================================
function action_untrash() {
    [ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	[ "${script_cat^^}" != "TRASH" ] && { echo -e "  ERROR: script are not in trash\n"; return 1; }

	local sp="${repository_path}/${script_name}/"
    [ -d "${sp}" ] && { echo -e "  ERROR: already exists script ${S_B}${script_name}${S_R}\n"; return 1; }

    read -r -p "  Sure? Script will be restore from trash (N/y) " r
    if [ "${r,,}" = "y" ]; then
        echo -e "  Restoring from trash script ${S_B}${f}${S_R}"
		mv "${script_path}" "${sp}" || return 1
        echo "UNTRASH" > "${sp}/category"

		script_cat="UNTRASH"
	    script_path="${sp}"
    fi
    echo
}


#=== FUNCTION ==================================================================
#        NAME: action_priority
# DESCRIPTION: action to toogle priority flag on selected script
#===============================================================================
function action_priority() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local f="${script_path}/priority"

	if [ -e "${f}" ]; then
		echo -e "  Disabling priority flag ${S_B}${f}${S_R}"
		rm -f "${f}"
	else
		echo -e "  Enabling priority flag ${S_B}${f}${S_R}"
		touch "${f}"
	fi
	echo
}


#=== FUNCTION ==================================================================
#        NAME: action_first
# DESCRIPTION: action to toogle first flag on selected script
#===============================================================================
function action_first() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local f="${script_path}/first"

	if [ -e "${f}" ]; then
		echo -e "  Disabling first flag ${S_B}${f}${S_R}"
		rm -rf "${f}"
	else
		echo -e "  Enabling first flag ${S_B}${f}${S_R}"
		touch "${f}"
	fi
	echo
}

#=== FUNCTION ==================================================================
#        NAME: action_nosavelog
# DESCRIPTION: action to toogle nosavelog flag on selected script
#===============================================================================
function action_nosavelog() {
    [ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
    local f="${script_path}/nosavelog"

    if [ -e "${f}" ]; then
        echo -e "  Disabling nosavelog flag ${S_B}${f}${S_R}"
        rm -r "${f}"
    else
        echo -e "  Enabling nosavelog flag ${S_B}${f}${S_R}"
        touch "${f}"
    fi
	echo
}




#=== FUNCTION ==================================================================
#        NAME: action_ls
# DESCRIPTION: action to list all files of selected script
#===============================================================================
function action_ls() {
	[ ! "$script_name" ] && { echo -e "  ERROR: no script selected\n"; return 1; }
	local f="${script_path}"
	echo -e "\n  ${f}${C_LN}"
	ls -lh --color "$f" | tail -n +2
	echo -e "${C_D}"
}

#=== FUNCTION ==================================================================
#        NAME: action_..
# DESCRIPTION: action deselect selected script
#===============================================================================
function action_..() {
	unset script_name
	unset script_cat
	unset script_path
}


#=== FUNCTION ==================================================================
#        NAME: help
# DESCRIPTION: Print help and exit 
#  PARAMETERS:
#	$1	Exit code value
#===============================================================================
function help() {
	echo -e "Usage: $(basename "$0") [repository]"
	exit "$1"
}


#=== FUNCTION ==================================================================
#        NAME: main
# DESCRIPTION: main
#===============================================================================
function main()  {
    # FORCE lss-admin USER                                                                                
    if [ ! $(id -un) = "lss-admin" ]; then
        if [ $(id -u) -eq 0 ]; then
            exec runuser -u lss-admin -- "$0" "$@"
        else
            echo "ERROR: lss-manager must be executed has lss-admin user"
            exit 1
        fi
    fi

	local r="linux"	# Default repository linux
	local p="$1"

	case "$p" in
		-h)	help 1		;;
		"") r="linux"	;;
		*)	r="$1"		;;
	esac

	# SET REPOSITORY
	change_repository "$r" || { echo "Invalid repository"; exit 1; }

	# MAIN LOOP
	while true; do
		read_action
		exec_action
	done
}
main "$@"
