#!/usr/bin/env bash
#===================================================================================
# LABADMIN SCRIPT SERVER
#         FILE: lss-srv
#        USAGE: lss-srv -h hostname -M mac -r repository_name -a list|get|exec_ok|exec_error [-s script] [-m exec_message] [-v version]
#
#  DESCRIPTION: Labadmin Script Server
#               Manage actions to do: list pending scripts, print script code, save exec status (exec_ok or exec_error)
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#	   LICENSE: GNU General Public License v3.0
#      VERSION: 2026.04
#      CREATED: 2022.06.28
#=================================================================================== 

#===============================================================================
#  GLOBAL VARIABLES
#===============================================================================
readonly lss_path=$(dirname "$(readlink -f "$0")")			# LSS root path
readonly lssinventory_path="${lss_path}/lss-inventory"		# lss-inventory executable path

unset log_mail												# log mail                        (loaded in config file)
unset repositories_path										# repositories path               (loaded in config file)

unset hostname												# hostname parameter
unset hostname_inventory									# hostname from lss-inventory (matching with mac)
unset hostname_match										# not empty if hostname parameter matches with hostname inventory
unset hostname_error										# not empty if not found hostname inventory for given mac
unset mac													# mac parameter
unset repository											# repository parameter
unset repository_path										# repository path
unset action												# action parameter
unset script												# script parameter
unset script_path											# script path
unset exec_msg												# exec_msg parameter
unset agent_version											# agent LSS version


#===============================================================================
#  LOAD CONFIG
#===============================================================================
source "${lss_path}/config"									# LOAD CONFIG VARIABLES




#=== FUNCTION ==================================================================
#        NAME: help
# DESCRIPTION: Print help and exit 
#  PARAMETERS:
#	$1	Exit code value
#===============================================================================
function help() {
	echo -e "Usage: $(basename "$0") -h hostname -M mac -r repository_name -a list|get|exec_ok|exec_error [-s script] [-m exec_message]"
	exit "$1"
}


#=== FUNCTION ==================================================================
#        NAME: check_params
# DESCRIPTION: Checks input parameters and load values
#  PARAMETERS:
#	$@	All parameter from command line
#===============================================================================
function check_params() {
	while getopts ":h:M:r:a:s:m:v:" option
	do
		case $option in
		h)
			readonly hostname="$OPTARG"
		;;
		M)
			mac=$(echo "${OPTARG,,}" | tr "-" ":")
		;;
		r)
			readonly repository="$OPTARG"
			readonly repository_path="${repositories_path}/${repository}/"
		;;
		a)
			readonly action="$OPTARG"
		;;
		s)
			readonly script="$OPTARG"
			readonly script_path="${repository_path}/${script}"
		;;
		m)
			readonly exec_msg="$OPTARG"
		;;
		v)
			agent_version="$OPTARG"
		;;
		?)
			echo "Incorrect option: $OPTARG"
			exit 2
		;;
	   esac
	done

	if [ $# -eq 0 ]; then
		help 1
	elif [ ! "$hostname" ]; then
		echo "ERROR: Hostname not present" 1>&2
		help 2
	elif [ ! "$mac" ]; then
		echo "ERROR: MAC not present" 1>&2
		help 2
	elif [ "${mac#[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]}" ]; then
		echo "ERROR: Invalid MAC" 1>&2
		help 2
	elif [ ! "$repository" ]; then
	    echo "ERROR: Repository not present" 1>&2
		help 2
	elif [ ! "$action" ]; then
	    echo "ERROR: Action not present" 1>&2
		help 2
	elif  [[ "$action" != @(list|get|exec_ok|exec_error) ]]; then
	    echo "ERROR: Invalid action value" 1>&2
		help 2
	elif [[ "$action" = @(get|exec_ok|exec_error) ]] && [ ! "$script" ]; then
		echo "ERROR: Script not present" 1>&2
		help 2
	elif [ ! -d "$repositories_path" ] || [ ! -r "$repositories_path" ]; then
		echo "ERROR: Cant access repositories path: $repositories_path" 1>&2
		exit 2
	elif [ ! -d "$repository_path" ] || [ ! -r "$repository_path" ]; then
		echo "ERROR: Cant access repository path: $repository_path" 1>&2
		exit 2
	elif [ "$script" ] && ([ ! -d "$script_path" ] || [ ! -r "$script_path" ]); then
		echo "ERROR: Cant access script path: $script_path" 1>&2
		exit 2
	elif [ ! "$agent_version" ]; then
		agent_version="0"
	fi
}


#=== FUNCTION ==================================================================
#        NAME: log
# DESCRIPTION: write in ${script_path}/log file using format: [DATE TIME] [MAC] [HOSTNAME] [ACTION] EXEC_MSG
#			   and send mail log
#  PARAMETERS:
#		$1: mac
#		$2: hostname
#		$3: action
#		$4: script path
#		$5: exec_msg
#===============================================================================
function log() {
	local m="$1"                      # mac
	local hn="$2"                     # hostname
	local a="$3"                      # action
	local sp="$4"                     # script path
	local em="$5"                     # exec message
	local sn=$(basename "$sp")        # script name

	# SAVE FILE
	[ ! "$sp" ] && sp="${repository_path}"  # Save script log or lss log
	local d=$(date "+%Y-%m-%d_%H:%M:%S") pad10="          " pad12="           "

	# Save exec output in dedicated file
	if [[ "${a^^}" = EXEC* ]] && [ "$em" ]; then
		# NOSAVELOG flag > Save first line on main log
		if [ -f "${sp}/nosavelog" ]; then
			em="$(echo ${em//$'\n'/ / } | cut -c 1-100) ..."
		# Save log dedicated file
		else
			log_path="${sp}/logs/[$(echo "$d" | tr ":" ".")][${hn}][${a^^}].log"
			[ ! -d "${sp}/logs" ] && mkdir -p "${sp}/logs"
			echo "$em" > "$log_path"
			em="'${log_path}'"
		fi
	fi

	# Save action in main log
	echo -e "[${d}] [${m}] [${hn^^}]${pad10:${#hn}}[${a^^}]${pad12:${#a}} ${em}" >> "${sp}/log"

	# SEND MAIL
	if [[ "${a,,}" = *error* ]]; then
		echo -e "Date: $(date "+%Y-%m-%d %H:%M:%S")\nMAC: ${m}\nHostname: ${hn}\n$([ "$sn" ] && echo "Script: ${sn}\n")Action: ${a}\nError msg: ${em}" | mail -s "【script-server】【${sn:-$a}】" -a "From: ${hn}<${hn}@carlos3.com>" "$log_mail"
	fi
}


#=== FUNCTION ==================================================================
#        NAME: get_hostname_inventory
# DESCRIPTION: Get hostname from inventory given MAC and write in global variable hostname_inventory
#              and check if matches with hostname parameter
#  PARAMETERS:
#		$1: mac
#
# GLOBAL VARIABLES MODIFIED
#		$hostname_inventory		hostname inventory name for given mac
#		$hostname_match			no empty if hostname parameter matches with hostname inventory
#		$hotname_error			no empty if hostname not found for given mac
#
# EXIT CODE
#		0 if found hostname for mac
#		1 if not found hostname for mac
#===============================================================================
function get_hostname_inventory() {
	local m="$1"
	unset hostname_inventory hostname_match

	# Call to lss-inventory
	hostname_inventory=$(bash "${lssinventory_path}" get-hostname "$m" 2>/dev/null); local r=$?

	# Check hostname charset
	if [ "$hostname_inventory" ] && ! [[ "$hostname_inventory" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]; then
		log "$mac" "$hostname" "MAC_ERROR" "" "Error inventory: invalid charset hostname $hostname_inventory for MAC: $mac"
		echo "ERROR: invalid charset hostname $hostname_inventory for MAC: $mac" 1>&2
		exit 1
	fi

	# Update hostname_match
	[ "$hostname" = "$hostname_inventory" ] && hostname_match="true" || unset hostname_match

	# Update hostname_error
	[ "$r" -eq 0 ] && unset hostname_error || hostname_error="true"

	return $r
}



#=== FUNCTION ==================================================================
#        NAME: action_list
# DESCRIPTION: List all pending scripts for hostname according script name and select script
#===============================================================================
function action_list() {
	# GET INVENTORY HOSTNAME
	get_hostname_inventory "$mac" 

	# CHECK HOSTNAME
	if [ "$hostname_error" ]; then
		log "$mac" "$hostname" "MAC_ERROR" "" "Error inventory: no hostname found for MAC: $mac"
		echo "ERROR: no hostname found for MAC: $mac" 1>&2
		exit 1
	fi
	if [ ! "$hostname_match" ]; then
		log "$mac" "$hostname" "MAC_WARN" "" "Hostname mismatch for MAC $mac: current $hostname -> inventory $hostname_inventory)"
		echo "WARNING: hostname mismatch for MAC $mac: current $hostname -> inventory $hostname_inventory" 1>&2
		hostname_effective="$hostname_inventory"
	else
		hostname_effective="$hostname"
	fi

	# LIST PENDING SCRIPTS
	IFS2="$IFS"; IFS=$'\n'
	local list="" priority_list=""
	for s in $(ls "$repository_path"); do
		local sre="${s%% *}"						# script regular expresión (script dir name before first space)
		local sn="${s#* }"							# script name (script dir name afetr first space)
		local sp="${repository_path}/${s}"			# script path

		# Check repository directory format
		[ ! -d "${sp}" ] || [ ! "$sn" ] || [ ! "${sre}" ] && continue

		# Check hostname match with script REGEX
		[[ "${hostname_effective,,}" = ${sre,,} ]] || continue		# If no match continue

		# Check script is disabled
		[ -e "${sp}/disable" ] && continue

		# Check hostname is selected
		bash "${sp}/select" "$hostname" "$mac" "$hostname_inventory" "$agent_version" || continue

		# Check priority script
		[ "$priority_list" ] && [ ! -e "${sp}/priority" ] && continue
		[ ! "$priority_list" ] && [ -e "${sp}/priority" ] && { priority_list="true"; unset list; }

		# Add client options after script name: ... /OPTION1 /OPTION2 ...
		if [ "$agent_version" -ge 20260200 ]; then
			[ -f "${sp}/nosavelog" ] && s="${s} /NOSAVELOG"
		fi

		# Add script to list
		if [ -f "${sp}/first" ]; then			# FIRST script -> add first on list
			list="${s}${list:+$'\n'}${list}"
		else
			list="${list}${list:+$'\n'}${s}"
		fi
	done
	IFS="$IFS2"

	# Print selected scripts list
	echo "$list"

	# Log list
	log "$mac" "$hostname" "LIST" "" "|$(echo "$list" | cut -f2- -d" " | tr $'\n' "|")"
}


#=== FUNCTION ==================================================================
#        NAME: action_get
# DESCRIPTION: Print script code, log action and exit
#              Replace special strings in script content
#===============================================================================
function action_get() {
	local em

	# GET SCRIPT
	local c=$(cat "${script_path}/script")
	if [ $? -ne 0 ]; then
		log "$mac" "$hostname" "get_error" "$script_path" "Error reading script $script_path"
		exit 1
	fi

	# GET INVENTORY HOSTNAME
	get_hostname_inventory "$mac" 

	# REPLACE SCPECIAL STRINGS: 
	#   * LSS-HOSTNAME-REPLACE
	#   * LSS-MAC-REPLACE
	c=$(echo "$c" | sed "s/LSS-HOSTNAME-REPLACE/${hostname_inventory}/g")
	c=$(echo "$c" | sed "s/LSS-MAC-REPLACE/${hostname_inventory}/g")
	em="${hostname} -> ${hostname_inventory}"

	# PRINT SCRIPT
	echo "$c"
	log "$mac" "$hostname" "$action" "$script_path" "$em"
	exit 0
}



#=== FUNCTION ==================================================================
#        NAME: action_exec_ok
# DESCRIPTION: Notify correct execution
#===============================================================================
function action_exec_ok() {
	log "$mac" "$hostname" "$action" "$script_path" "$exec_msg"
}


#=== FUNCTION ==================================================================
#        NAME: action_exec_error
# DESCRIPTION: Notify error execution
#===============================================================================
function action_exec_error() {
	log "$mac" "$hostname" "$action" "$script_path" "$exec_msg"
}



##### CHECK PARAMETERS
check_params "$@"


##### EXEC ACTION
case "$action" in
	list)		action_list			;;
	get)		action_get			;;
	exec_ok)	action_exec_ok		;;
	exec_error)	action_exec_error	;;
esac
